int** init_mat(int w, int h);
int** init_mur(int** laby, int w, int h);
int** init_bord(int** laby, int w, int h);
void show_laby(int** laby, int w, int h);
void show_freq(int** freq, int w, int h); 
int next_col(int pos_x, int dir);
int next_line(int pos_y, int dir);
int cherche_mur(int** laby, int w, int h);
int** insere_joueur(int** laby, int w, int h, int pos_y, int pos_x);
int cherche_vide(int** laby, int w, int h);
int** insere_ia(int** laby, int w, int h, int pos_y, int pos_x);
int** deplace_ia(int** laby, int w, int h, int old_y, int old_x, int direction);
int est_case_vide(int** laby, int direction, int old_y, int old_x); 
int ia_cherche_deplacement(int** laby, int old_y, int old_x); 
int ia_nouveau_deplacement_rand(int** laby, int old_y, int old_x, int old_dir); 
int** fabrique_mat_frequence(int** laby, int** freq, int w, int h);
int** remplir_mat_frequence(int** freq, int pos_y, int pos_x);
int** trace_obstacles(int** laby, int w, int h); 
